options:
  port: 
    type: int
    default: 8070
    description: "Port for the admin-ui to listen to."
  repository:
    type: string
    default: "https://github.com/allomov/admin-ui.git"
    description: "Github repository of admin-ui that is used to clone project."
  branch:
    type: string
    default: 'juju-charm-version'
    description: "Git branch of amdin-ui project to fetch."
  commit:
    type: string
    default: ''
    description: | 
        Commit SHA to use when getting source code for admin-ui. 
        If it is empty, the latest commit in a branch is used.
