options:
  port: 
    type: int
    default: 8070
    description: "Port for the admin-ui to listen to."
  repository:
    type: string
    default: "https://github.com/cloudfoundry-incubator/admin-ui.git"
    description: "Github repository of admin-ui that is used to clone project."
  commit:
    type: string
    default: '0d56f45280537e87c90b9c61c6340293ce0446a0'
    description: "Commit SHA to use when getting source code for admin-ui."
