#!/usr/bin/env python
# from charmhelpers.core import services
# import config

# manager = services.ServiceManager(config.SERVICES)
# manager.manage()

# Consider to redeploy Admin UI because there are only repository options in config
