---
bind_address: 0.0.0.0
ccdb_uri: mysql2://{{ ccdb[0]['user'] }}:{{ ccdb[0]['password'] }}@{{ ccdb[0]['host'] }}:{{ ccdb[0]['port'] }}/{{ ccdb[0]['database'] }}
cloud_controller_discovery_interval: 300
cloud_controller_ssl_verify_none: false
cloud_controller_uri: http://api.{{ router[0]['domain'] }}
component_connection_retries: 2
data_file: data/data.json
db_uri: sqlite://data/store.db
log_file: admin_ui.log
log_file_page_size: 51200
log_file_sftp_keys: [ ]
log_files: [/var/vcap/sys/log/cloud_controller_ng/*.log, admin_ui.log]
mbus: nats://{{ nats[0]["user"] }}:{{ nats[0]["password"] }}@{{ nats[0]["address"] }}:{{ nats[0]["port"] }}
monitored_components: [NATS, CloudController, DEA, HealthManager, Router, -Provisioner, ALL]
nats_discovery_interval: 30
nats_discovery_timeout: 10
port: {{ port }}
receiver_emails: [ ]
sender_email:
  server: 10.10.10.10
  account: system@10.10.10.10
stats_file: data/stats.json
stats_refresh_schedules: [ '0 5 * * *' ]
stats_retries: 5
stats_retry_interval: 300
tasks_refresh_interval: 5000
uaa_client:
  id: admin_ui_client
  secret: admin_ui_secret
uaadb_uri: mysql2://{{ uaadb[0]['user'] }}:{{ uaadb[0]['password'] }}@{{ uaadb[0]['host'] }}:{{ uaadb[0]['port'] }}/{{ uaadb[0]['database'] }}
uaa_groups_admin: [ admin_ui.admin ]
uaa_groups_user: [ admin_ui.user ] 
varz_discovery_interval: 30
